name: Gcloud CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: testapp
  CPU: 1
  MEMORY: 256Mi


jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]

    runs-on: ${{ matrix.os }}
    steps:
      # Setup JDK
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}

      # Cache node modules
      - name: Cache pnpm packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.vaadin
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml', '**/package.json') }}

      # Maven build
      - name: Build with Maven
        run: mvn clean package -Pproduction -DskipTests

      # Creating new directory and copying jar to new folder how artifact for future using
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging


      # Setup gcloud CLI
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID

      # Build Cloud Run project
      - name: GCP Build
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA


      # Deploy image to Cloud Run with JIB
      - name: GCP Deploy
        run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:dockerBuild \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated \
          --region $RUN_REGION \
          --memory=$MEMORY \
          --cpu=$CPU \
