name: Gcloud CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: testapp
  CPU: 2
  MEMORY: 2Gi
  SA_EMAIL: ${{ secrets.SA_EMAIL }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]

    runs-on: ${{ matrix.os }}
    steps:
      # Setup JDK
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties') }}

      # Cache node modules
      - name: Cache pnpm packages
        uses: actions/cache@v1
        with:
          path: |
            ~/.vaadin
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml', '**/package.json') }}

      # Maven build
      - name: Build with Maven
        run: mvn clean package -Pproduction -DskipTests

      # Creating new directory and copying jar to new folder how artifact for future using
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging


      # Setup gcloud CLI
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: $SA_EMAIL
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure gcloud CLI
      - name: gcloud Set up
        run: |
          gcloud config set project $PROJECT_ID

      #Authentication gcloud CLI
      - name: Authentication GC Service account
        run: |
          gcloud auth activate-service-account $SA_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS


      # Building GC Java containers with Jib
      - name: GCP Build
        run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build \
                -Dimage=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Deploy image to Cloud Run
      - name: GCP Deploy
        run: |
          gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated \
          --region $RUN_REGION \
          --memory=$MEMORY \
          --cpu=$CPU \
